### ISSUE TITLE
KaminoApiClient error: Protocol message end-group tag did not match expected tag

### ISSUE THREAD

**Issue by jtjeferreira** [kamino-apm/kamino-reporter#8]
When updating to kamino-reporter 1.1.0, we are having these errors:

```
[ERROR] undefined NO_WL k.k.KaminoApiClient - Connection error, retrying... (20 left) Protocol message end-group tag did not match expected tag. 
```

**Comment by ivantopo** [comment]
Hey @jtjeferreira, did that happen between 12:42 and 12:55 UTC today?

**Comment by jtjeferreira** [comment]
Yes. It started `12:42:25` and ended `12:55:05`, but it only happened in the environment where we updated the reporter...
